version: '3.8'

name: eduspace_mobile
services:
  mongodb:
    image: mongo:8.0
    container_name: mongodb_mobile
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-eduspace}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-eduspace123}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-eduspacedb}
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongodb_data_mobile:/data/db
    networks:
      - eduspace-network

volumes:
  mongodb_data_mobile:
    driver: local

networks:
  eduspace-network:
    driver: bridge

